<!DOCTYPE html>
<html lang="en">
	<head>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">

		<title><?php echo $config->title; ?></title>

		<!-- Bootstrap Core CSS -->
		<link href="<?php echo $theme->getUrl(); ?>/css/bootstrap.min.css" rel="stylesheet">

		<!-- Custom CSS -->
		<link href="<?php echo $theme->getUrl(); ?>/css/heroic-features.css" rel="stylesheet">

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

		<?php echo isset($headers) ? $headers : ''; ?>

		<style>
	/*		.navbar {
				background-color: #4d4d4d !important;
			}

			.nav a {
				color: white !important;
			}*/

		</style>
	</head>

	<body>
		<nav style="position: fixed; top: 0px; width: 100%; height: 50px; background-color: #333; margin-bottom: 0px; z-index: 50;" role="navigation">
			<div class="container" style="height: 50px; line-height: 50px;">
	<!--			<div class="title"><?php echo $config->name; ?></div>-->
				<span style="text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.75); font-family: 'Open Sans', sans-serif; font-size: 24px; font-weight: 600; color: white;"><?php echo isset($config->name) ? $config->name : ''; ?></span>
				<span style="margin-left: 20px; font-family: 'Open Sans', sans-serif; font-size: 14px; font-style: italic; font-weight: 300; color: #f3f4f5;">Flexible, lightweight PHP application framework</span>
			</div>
		</nav>
		<nav class="smenu-nav navbar-default" style="" role="navigation">
			<div class="container" style="height: 30px;">
				<ul class="nav navbar-nav">
				<?php if (isset($menus)): ?>
				<?php foreach ($menus as $name => $menu): ?>
				<?php if (isset($menu['children']) && is_array($menu['children'])): ?>
					<li class="dropdown">
						<a href="<?php echo $menu['url']; ?>" data-toggle="dropdown" class="dropdown-toggle"><?php echo $name; ?> <b class="caret"></b></a>
						<ul class="dropdown-menu">
						<?php foreach($menu['children'] as $cname => $child): ?>
							<li><a href="<?php echo $child['url']; ?>"><?php echo $cname; ?></a></li>
						<?php endforeach; ?>
						</ul>
					</li>
				<?php else: ?>
					<li><a href="<?php echo $menu['url']; ?>"><?php echo $name; ?></a></li>
				<?php endif; ?>
				<?php endforeach; ?>
				<?php endif; ?>
				</ul>
			</div>
		</nav>
	<!--	<nav sclass="navbar navbar-inverse navbar-fixed-top" style="margin-bottom: 0px;" role="navigation">
			<div class="container" style="height: 30px;">
				dd
			</div>
		</nav>-->

	<!--    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">

				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>

						<div class="title"><?php echo $config->name; ?></div>

				</div>

				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
					<?php foreach ($menus as $name => $menu): ?>
					<?php if (isset($menu['children']) && is_array($menu['children'])): ?>
						<li class="dropdown">
							<a href="<?php echo $menu['url']; ?>" data-toggle="dropdown" class="dropdown-toggle"><?php echo $name; ?> <b class="caret"></b></a>
							<ul class="dropdown-menu">
							<?php foreach($menu['children'] as $cname => $child): ?>
								<li><a href="<?php echo $child['url']; ?>"><?php echo $cname; ?></a></li>
							<?php endforeach; ?>
							</ul>
						</li>
					<?php else: ?>
						<li><a href="<?php echo $menu['url']; ?>"><?php echo $name; ?></a></li>
					<?php endif; ?>
					<?php endforeach; ?>
					</ul>
				</div>
			</div>
		</nav>-->

		<!-- Page Content -->
		<div class="container">
			<?php echo $content; ?>

			<hr>

			<pre><?php print_r($request); ?></pre>

			<!-- Footer -->
			<footer>
				<div class="row">
					<div class="col-lg-12">
						<p>Copyright &copy; devforge.org 2015</p>
					</div>
				</div>
			</footer>

		</div>
		<!-- /.container -->

		<!-- jQuery -->
		<script src="<?php echo $themeUrl; ?>/js/jquery.js"></script>

		<!-- Bootstrap Core JavaScript -->
		<script src="<?php echo $themeUrl; ?>/js/bootstrap.min.js"></script>

		<?php echo isset($footers) ? $footers : ''; ?>
	</body>
</html>