<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">

		<title><?php echo $config->title; ?></title>

		<!-- Defaults CSS -->
		<link href="<?php echo $theme->getUrl(); ?>/css/defaults.css" rel="stylesheet">

		<!-- Bootstrap Core CSS -->
		<link href="<?php echo $this->application->getAppUrl(); ?>/css/bootstrap.min.css" rel="stylesheet">

		<!-- Font Awesome -->
		<link href="<?php echo $this->application->getAppUrl(); ?>/css/font-awesome.min.css" rel="stylesheet">

		<!-- jQuery -->
		<script src="<?php echo $this->application->getAppUrl(); ?>/js/jquery.js"></script>

		<!-- Bootstrap Core JavaScript -->
		<script src="<?php echo $this->application->getAppUrl(); ?>/js/bootstrap.min.js"></script>

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

		<?php echo isset($headers) ? $headers : ''; ?>

		<style>
			body {
				padding-top: 48px;
			}

			@media (min-width: 850px) {
				.navbar-collapse {
					background-color: #E6E6E6;
				}
			}

			@media (min-width: 1200px) {
				.container {
					width: 100%;
				}
			}

			.navbar-collapse {
/*				padding-left: 0px;
				padding-right: 0px;*/
			}

			.container .content {
				padding-right: 15px;
				padding-left: 15px;
			}
		</style>
	</head> 
	<body>

		<nav class="navbar navbar-inverse navbar-fixed-top" style="margin-bottom: 0px !important; border-bottom-width: 0px;">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" style="background-color: maroon;">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#" style="background-color: maroon; color: white;"><?php echo $config->name; ?></a>
				</div>
				<div id="tnavbar" class="">

				</div><!--/.nav-collapse -->
			</div><!--/.container-fluid -->
		</nav>
<!--		<nav class="navbar navbar-collapse" style="padding-left: 0px !important; padding-right: 0px !important; border-left-width: 0px !important; border-right-width: 0px !important; ">
			<div class="container-fluid">-->
				<div id="navbar" class="navbar-collapse collapse">
					<?php echo key_exists('top', $menus) ? getMenu($menus['top']) : ''; ?>
					<?php echo key_exists('topRight', $menus) ? getMenu($menus['topRight'], 'right') : ''; ?>
				</div>
<!--			</div>
		</nav>-->

		<div class="container" style="padding-left: 0px; padding-right: 0px;">

			<?php echo $content; ?>

			<hr>

			<footer>
				<div class="row">
					<div class="col-lg-12">
						<p>©2016 Devforge Inc. All rights reserved</p>
					</div>
				</div>
			</footer>
		</div>
	</body>
</html><?php

function getMenu($menus, $orientation='') {
	$data = '';
	sortMenu($menus);
	foreach ($menus as $menu) {
		$data .= buildMenu($menu, 1, $orientation);
	}
	return $data;
}

function buildMenu($menu, $level = 1, $orientation='') {
	$data = '';
	if ($level === 1) {
		$data .= '<ul class="nav navbar-nav ' . (($orientation === 'right') ? 'navbar-right' : '') . ((key_exists('class', $menu)) ? $menu['class'] : '') . '">';
	}

	$sub = false;
	$class = '';
	if (key_exists('children', $menu) && !empty($menu['children'])) {
		$sub = true;
	}

	if ($sub && $level > 1) {
		$data .= '<li class="dropdown-submenu ' . (($orientation === 'right') ? 'navbar-right' : '') . '">';
	} else if ($sub) {
		$data .= '<li class="dropdown">';
		$class = ' class="dropdown-toggle" data-toggle="dropdown"';
	} else {
		$data .= '<li>';
	}
	$data .= '<a href="' . (isset($menu['uri']) ? $menu['uri'] : '#') . '" ' . $class . '>' . $menu['title'];

	if ($sub) {
		$data .= ' <b class="caret"></b></a>';

		$sub = false;
		$subcontent = '';
		foreach ($menu['children'] as $submenu) {
			if (key_exists('children', $submenu) && !empty($submenu['children'])) {
				$sub = true;
				sortMenu($submenu['children']);
			}
			$subcontent .= buildMenu($submenu, $level+1, $orientation);
		}

		if ($sub) {
			$data .= '<ul class="dropdown-menu multi-level ' . (($orientation === 'right') ? 'pull-right' : '') . '">';
		} else {
			$data .= '<ul class="dropdown-menu">';
		}
		$data .= $subcontent;
		$data .= '</ul>';
	} else {
		$data .= '</a>';
	}

	$data .= '</li>';
	if ($level === 1) {
		$data .= '</ul>';
	}
	return $data;
}

function sortMenu(&$menu) {
	usort($menu, 'sortGroup');
}

function sortGroup($a, $b) {
	$group = strcasecmp(isset($a['group']) ? $a['group'] : 'default', isset($b['group']) ? $b['group'] : 'default');
	if ($group === 0) {
		$priority = ((isset($a['priority']) ? $a['priority'] : 1) - (isset($b['priority']) ? $b['priority'] : 1));
		if ($priority === 0) {
			return strcasecmp($a['title'], $b['title']);
		}
		return $priority;
	}
	return $group;
}