<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">

		<title><?php echo $config->title; ?></title>

		<!-- Defaults CSS -->
		<link href="<?php echo $theme->getUrl(); ?>/css/defaults.css" rel="stylesheet">

		<!-- Bootstrap Core CSS -->
		<link href="<?php echo $this->application->getAppUrl(); ?>/css/bootstrap.min.css" rel="stylesheet">

		<!-- Font Awesome -->
		<link href="<?php echo $this->application->getAppUrl(); ?>/css/font-awesome.min.css" rel="stylesheet">

		<!-- jQuery -->
		<script src="<?php echo $this->application->getAppUrl(); ?>/js/jquery.js"></script>

		<!-- Bootstrap Core JavaScript -->
		<script src="<?php echo $this->application->getAppUrl(); ?>/js/bootstrap.min.js"></script>

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

		<?php echo isset($headers) ? $headers : ''; ?>

	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#"><?php echo $config->name; ?></a>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

					<ul class="nav navbar-nav navbar-right">
						<li><a href="#">Menu</a></li>
					</ul>
				</div>
			</div>
		</nav>

		<div class="container">
			<?php echo $content; ?>

			<hr>

			<footer>
				<div class="row">
					<div class="col-lg-12">
						<p>©2016 Devforge Inc. All rights reserved</p>
					</div>
				</div>
			</footer>
		</div>
	</body>
</html>