<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">

		<title><?php echo $config->title; ?></title>

		<!-- Defaults CSS -->
		<link href="<?php echo $theme->getUrl(); ?>/css/defaults.css" rel="stylesheet">

		<!-- Bootstrap Core CSS -->
		<link href="<?php echo $this->application->getAppUrl(); ?>/css/bootstrap.min.css" rel="stylesheet">

		<!-- Font Awesome -->
		<link href="<?php echo $this->application->getAppUrl(); ?>/css/font-awesome.min.css" rel="stylesheet">

		<!-- jQuery -->
		<script src="<?php echo $this->application->getAppUrl(); ?>/js/jquery.js"></script>

		<!-- Bootstrap Core JavaScript -->
		<script src="<?php echo $this->application->getAppUrl(); ?>/js/bootstrap.min.js"></script>

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

		<?php echo isset($headers) ? $headers : ''; ?>

	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<?php echo $this->application->getAppUrl(); ?>"><?php echo $config->name; ?></a>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<?php echo key_exists('top', $menus) ? getMenu($menus['top']) : ''; ?>
				</div>
			</div>
		</nav>

		<div class="container">
			<?php echo $content; ?>

			<hr>

			<footer>
				<div class="row">
					<div class="col-lg-12">
						<p>©2016 Devforge Inc. All rights reserved</p>
					</div>
				</div>
			</footer>
		</div>
	</body>
</html><?php

function getMenu($menus) {
	$data = '';
	sortMenu($menus);
	foreach ($menus as $menu) {
		$data .= buildMenu($menu);
	}
	return $data;
}

function buildMenu($menu, $level = 1) {
	$data = '';
	if ($level === 1) {
		$data .= '<ul class="nav navbar-nav ' . ((key_exists('class', $menu)) ? $menu['class'] : '')   . '">';
	}

	$sub = false;
	$class = '';
	if (key_exists('children', $menu) && !empty($menu['children'])) {
		$sub = true;
	}

	if ($sub && $level > 1) {
		$data .= '<li class="dropdown-submenu">';
	} else if ($sub) {
		$data .= '<li class="dropdown">';
		$class = ' class="dropdown-toggle" data-toggle="dropdown"';
	} else {
		$data .= '<li>';
	}
	$data .= '<a href="' . (isset($menu['uri']) ? $menu['uri'] : '#') . '" ' . $class . '>' . $menu['title'];

	if ($sub) {
		$data .= ' <b class="caret"></b></a>';

		$sub = false;
		$subcontent = '';
		foreach ($menu['children'] as $submenu) {
			if (key_exists('children', $submenu) && !empty($submenu['children'])) {
				$sub = true;
				sortMenu($submenu['children']);
			}
			$subcontent .= buildMenu($submenu, $level+1);
		}

		if ($sub) {
			$data .= '<ul class="dropdown-menu multi-level">';
		} else {
			$data .= '<ul class="dropdown-menu">';
		}
		$data .= $subcontent;
		$data .= '</ul>';
	} else {
		$data .= '</a>';
	}

	$data .= '</li>';
	if ($level === 1) {
		$data .= '</ul>';
	}
	return $data;
}

function sortMenu(&$menu) {
	usort($menu, 'sortGroup');
}

function sortGroup($a, $b) {
	$group = strcasecmp(isset($a['group']) ? $a['group'] : 'default', isset($b['group']) ? $b['group'] : 'default');
	if ($group === 0) {
		$priority = ((isset($a['priority']) ? $a['priority'] : 1) - (isset($b['priority']) ? $b['priority'] : 1));
		if ($priority === 0) {
			return strcasecmp($a['title'], $b['title']);
		}
		return $priority;
	}
	return $group;
}